spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/mhs_test"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "mhs"
    password: "123456"
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5    
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  main:
    log-startup-info: false

server:
  port: 8080